apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-ci-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-ci-app
  template:
    metadata:
      labels:
        app: node-ci-app
    spec:
      containers:
      - name: node-ci-app
        image: praveenkreddy56/node-ci-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-ci-service
spec:
  type: NodePort
  selector:
    app: node-ci-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30007
